require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - '.pryrc'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/LambdaCall:
  Exclude:
    - app/views/**/*.jbuilder

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
    - lib/tasks/**/*.rake

Metrics/AbcSize:
  Exclude:
    - spec/support/**/*
    - db/migrate/**

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/**

Rails/NotNullColumn:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - scripts/upload_video.rb

RSpec/ChangeByZero:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    - spec/services/yandex/revise_other_dir_service_spec.rb
    - spec/services/yandex/revise_dir_service_spec.rb

RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

RSpec/PendingWithoutReason:
  Exclude:
    - spec/support/model_with_upload_workflow.rb
