require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'bin/**/*'
    - '.pryrc'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/LambdaCall:
  Exclude:
    - app/views/**/*.jbuilder

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - spec/support/**/*

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false
