ARG GO_VERSION=1.15.5

FROM golang:${GO_VERSION}-alpine as builder

RUN apk add git
RUN go get -u github.com/lib/pq

COPY proxy_service /proxy
WORKDIR /proxy
RUN go build -ldflags '-s -w' yandex_proxy.go

FROM alpine

RUN apk add --update --no-cache postgresql-client
COPY --from=builder /proxy/yandex_proxy /proxy/
COPY docker/photostorage/templates/wait_for_pg.sh /proxy/

WORKDIR /proxy
EXPOSE 9000

CMD ./wait_for_pg.sh && ./yandex_proxy -db_host=db -user=postgres -db=photos -listen=0.0.0.0
