ARG DOCKER_GO_VERSION
FROM golang:${DOCKER_GO_VERSION}-alpine as builder

RUN apk add git build-base vips-dev

COPY proxy_service /proxy
WORKDIR /proxy
RUN go build -ldflags '-s -w' proxy_service.go

FROM alpine

RUN apk add --update --no-cache vips-dev curl
COPY --from=builder /proxy/proxy_service /proxy/

WORKDIR /proxy
EXPOSE 9000
ENV PHOTOSTORAGE_PROXY_LISTEN=0.0.0.0:9000

CMD ./proxy_service
