FROM ruby:2.6.5-alpine

RUN apk add --no-cache tzdata nano libexif-dev openssh-client xz-dev libpq nodejs gcompat build-base
RUN cp /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime && echo 'Asia/Yekaterinburg' > /etc/timezone

RUN gem install bundler
RUN ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

ENV BUNDLE_APP_CONFIG /app/.bundle

WORKDIR /app
